version: "3.4"
services:
  bitbucket:
    image: "atlassian/bitbucket-server:latest"    
    container_name: bitbucket
    hostname: bitbucket
    restart: always
    environment:
      BITBUCKET_HOME: /var/atlassian/application-data/bitbucket/
      JAVA_OPTS: '-javacrack:/atlassian-crack.jar'
      JDBC_DRIVER: org.postgresql.Driver
      JDBC_URL: 'jdbc:postgresql://db:5432/bitbucket'
      JDBC_USER: bitbucket
      JDBC_PASSWORD: 'X&/LmRJDsw3wJf<30j39'
      JVM_MINIMUM_MEMORY: 512m
      JVM_MAXIMUM_MEMORY: 2048m

    volumes:
      - bitbucket-Data:/var/atlassian/application-data/bitbucket
      - ./crack/atlassian-agent.bak:/atlassian-crack.jar:ro
    networks:
      my-net:
       aliases:
        - bit
    ports:
      - 7990:7990
      - 7999:7999
  db:
    image: postgres:9.6
    container_name: bitbucket-database
    hostname: bitbucket-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'X&/LmRJDsw3wJf<30j39'
      POSTGRES_USER: bitbucket
      POSTGRES_DB: bitbucket
    volumes:
      - bitbucketDbVolume:/var/lib/postgresql/data
    networks:
      my-net:
       aliases:
        - bit-db        
        
volumes:
 bitbucket-Data:
   name: bitbucket-Data
 bitbucketDbVolume:
   name: bitbucketDbVolume

networks:
  my-net:



