version: "3.4"
services:
  confluence:
    image: atlassian/confluence-server:latest
    restart: always
    container_name: confluence
    hostname: confluence
    environment:      
      ATL_DB_TYPE: 'postgresql'
      ATL_JDBC_URL: 'jdbc:postgresql://db-con:5432/confluence'
      ATL_JDBC_USER: 'confluence'
      ATL_JDBC_PASSWORD: 'o3B5\U[4Edt03dBP/Miv'
      JAVA_OPTS: '-javacrack:/atlassian-crack.jar'
      JVM_MINIMUM_MEMORY: 512m
      JVM_MAXIMUM_MEMORY: 2048m

    volumes:
      - confluence-data:/var/atlassian/application-data/confluence
      - ./crack/atlassian-agent.bak:/atlassian-crack.jar:ro
    networks:
      my-net:
       aliases:
        - con
    ports:
      - 8090:8090
      - 8091:8091
    depends_on:
      - postgressql-confluence

  postgressql-confluence:
    image: postgres
    restart: always
    container_name: postgressql-confluence
    hostname: postgressql-confluence
    environment:
      POSTGRES_USER: confluence
      POSTGRES_PASSWORD: 'o3B5\U[4Edt03dBP/Miv'
      POSTGRES_DB: confluence
    volumes:
      - postgresql-data-con:/var/lib/postgresql/data
    networks:
      my-net:
       aliases:
        - db-con

networks:
  my-net:

volumes:
  postgresql-data-con:
    name: postgresql-data-con
  confluence-data:
    name: confluence-data