version: "3.4"
services:
  jira:
    image: atlassian/jira-software:latest
    restart: always
    container_name: jira
    hostname: jira
    environment:      
      ATL_DB_DRIVER: 'org.postgresql.Driver'
      ATL_DB_TYPE: 'postgres72'
      ATL_JDBC_URL: 'jdbc:postgresql://db-jira:5432/jira'
      ATL_JDBC_USER: 'jira'
      ATL_JDBC_PASSWORD: 'DA.13jpj93%eBw_Q'
      JAVA_OPTS: '-javaagent:/atlassian-agent.jar'
      JVM_MINIMUM_MEMORY: 512m
      JVM_MAXIMUM_MEMORY: 2048m

    volumes:
      - jira-vol:/var/atlassian/application-data/jira
      - ./agent/atlassian-agent.bak:/atlassian-agent.jar:ro
    networks:
      ronix-net:
    depends_on:
      - postgressql-jira
    ports:
      - 8081:8080

  postgressql-jira:
    image: postgres
    restart: always
    container_name: postgressql-jira
    hostname: postgressql-jira
    environment:
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: 'DA.13jpj93%eBw_Q'
    volumes:
      - postgresql-data-jira:/var/lib/postgresql/data
    networks:
      ronix-net:
       aliases:
        - db-jira

networks:
  ronix-net:

volumes:
  postgresql-data-jira:
    name: postgresql-data-jira
  jira-vol:
    name: jira-vol

